using Xamarin.Forms;
using Xamarin.Forms.Xaml;

[assembly: ExportFont("Quicksand-Light.ttf", Alias = "Brand-Light")]
[assembly: ExportFont("Quicksand-Medium.ttf", Alias = "Brand-Medium")]
[assembly: ExportFont("Quicksand-Regular.ttf", Alias = "Brand")]
[assembly: ExportFont("Quicksand-SemiBold.ttf", Alias = "Brand-SemiBold")]
[assembly: ExportFont("Quicksand-Bold.ttf", Alias = "Brand-Bold")]
[assembly: ExportFont("TitilliumWeb-ExtraLight.ttf", Alias = "Content-ExtraLight")]
[assembly: ExportFont("TitilliumWeb-ExtraLightItalic.ttf", Alias = "Content-ExtraLightItalic")]
[assembly: ExportFont("TitilliumWeb-Light.ttf", Alias = "Content-Light")]
[assembly: ExportFont("TitilliumWeb-LightItalic.ttf", Alias = "Content-LightItalic")]
[assembly: ExportFont("TitilliumWeb-Regular.ttf", Alias = "Content")]
[assembly: ExportFont("TitilliumWeb-Italic.ttf", Alias = "Content-Italic")]
[assembly: ExportFont("TitilliumWeb-SemiBold.ttf", Alias = "Content-SemiBold")]
[assembly: ExportFont("TitilliumWeb-SemiBoldItalic.ttf", Alias = "Content-SemiBoldItalic")]
[assembly: ExportFont("TitilliumWeb-Bold.ttf", Alias = "Content-Bold")]
[assembly: ExportFont("TitilliumWeb-BoldItalic.ttf", Alias = "Content-BoldItalic")]
[assembly: ExportFont("TitilliumWeb-Black.ttf", Alias = "Content-Black")]
[assembly: XamlCompilation(XamlCompilationOptions.Compile)]